### ISSUE TITLE
사람들은 왜 리액트에 열광할까?

### ISSUE THREAD

**Issue by Sookhee** [Sookhee/React-study-withMirim#3]
### 사람들은 왜 리액트에 열광할까?

1. 자바스크립트 기반
별도의 프레임워크를 공부할 필요 없이 자바스크립트와 약각의 html로 개발한ㄷ.

2. composition
리액트 구조는 요소별, 컴포넌트별로 나눠서 작업 가능.
모든걸 작은 요소(composition)로 쪼개서 작업하면 그것을 가져다 다른 곳에 쓸 수 있다.

3. 단방향(Unidirectional) 데이터 플로우
데이터는 그대로 있고 UI가 업데이트.
UI는 데이터를 변경하지 않음(only Data -> UI)

+ 방대한 커뮤니티, 오픈소스, 라이브러리, 질문과 대답.
+ 프레임워크 X. 라이브러리 O.
+ view이기 때문에 node.js, python, django, ruby 등 섞어서 사용 가능.

**Comment by Daria0412** [comment]
모르겠어요 ㅜㅜ
